# Generated by Django 5.0.6 on 2024-06-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('content', models.TextField()),
                ('department', models.IntegerField(choices=[(1, 'HR'), (2, 'IT'), (3, 'Sales')])),
                ('importance', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
