# Generated by Django 5.0.6 on 2024-06-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='importance',
            field=models.CharField(max_length=50),
        ),
    ]
