# Generated by Django 5.0.6 on 2024-06-20 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_department_alter_event_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='department',
        ),
        migrations.RemoveField(
            model_name='event',
            name='importance',
        ),
    ]
